services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    ports:
      - "25432:5432"
  rabbitmq:
    image: rabbitmq:management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "25672:5672"
      - "15672:15672"

  # -------------------------------------------
  # ZOOKEEPER (Required by Kafka)
  # -------------------------------------------
  # -------------------------------------------
  # KAFKA
  # -------------------------------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    environment:
      # Each broker in a cluster needs a unique ID
      KAFKA_BROKER_ID: 1

      # Point Kafka to Zookeeper
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # Internal & external communication settings
      # (Plaintext only, no SSL or SASL configured)
      KAFKA_LISTENERS: OUTSIDE://0.0.0.0:9094,INTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094,
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: OUTSIDE:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      # For a single-broker setup, set replication factor of 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  identity:
    ports:
      - 8081:8081
    depends_on:
      - kafka
      - rabbitmq
      - db
    build:
      context: ./identity
      dockerfile: ./src/main/docker/Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker

  post:
    ports:
      - 8082:8082
    depends_on:
      - kafka
      - rabbitmq
      - db
    build:
      context: ./post
      dockerfile: ./src/main/docker/Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker

  follow:
    ports:
      - 8083:8083
    depends_on:
      - kafka
      - rabbitmq
      - db
    build:
      context: ./follow
      dockerfile: ./src/main/docker/Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
  
  notification:
    ports:
      - 8084:8084
    depends_on:
      - kafka
      - rabbitmq
      - db
      - follow
      - post
    build:
      context: ./notification
      dockerfile: ./src/main/docker/Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker


  frontend:
    ports:
      - 3000:3000
    depends_on:
      - notification
    build:
      context: frontend
      dockerfile: Dockerfile
